// Thin re-exports of lucide-react with the prototype's naming convention.
// All icons: 24px viewBox, stroke-width 1.6, currentColor (lucide defaults match).
export {
  LayoutDashboard as IconDashboard,
  Briefcase       as IconBriefcase,
  Calendar        as IconCalendar,
  BarChart2       as IconStats,
  FileText        as IconFile,
  Users           as IconPeople,
  BookOpen        as IconNote,
  Bell            as IconBell,
  Search          as IconSearch,
  Plus            as IconPlus,
  ArrowRight      as IconArrowRight,
  ArrowUpRight    as IconArrowUpRight,
  ChevronLeft     as IconChevronLeft,
  ChevronRight    as IconChevronRight,
  ChevronDown     as IconChevronDown,
  Check           as IconCheck,
  Pencil          as IconEdit,
  Trash2          as IconTrash,
  ExternalLink    as IconExternal,
  Filter          as IconFilter,
  ArrowUpDown     as IconSort,
  Star            as IconStar,
  Clock           as IconClock,
  MapPin          as IconMapPin,
  DollarSign      as IconDollar,
  Link            as IconLink,
  MoreHorizontal  as IconMore,
  LogOut          as IconLogout,
  Sparkles        as IconSparkle,
  Paperclip       as IconAttach,
} from 'lucide-react';
